LOAD DATA LOCAL INFILE 'tableIdDomain.csv' INTO TABLE tableIdDomain FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'messagesForUsersDomain.csv' INTO TABLE messagesForUsersDomain FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'requestTypeDomain.csv' INTO TABLE requestTypeDomain FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
